apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rhdg8-caches
  annotations:
    description: Template to configure caches inside a RHDG cluster on OCP.
    tags: infinispan,datagrid,operator
    iconClass: icon-datagrid
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
objects:
- apiVersion: infinispan.org/v2alpha1
  kind: Cache
  metadata:
    name: ${CLUSTER_NAME}-operator-cache-98
    namespace: ${CLUSTER_NAMESPACE}
    labels:
      type: middleware
  spec:
    clusterName: ${CLUSTER_NAME}
    name:  operator-cache-98
    template: |
      invalidationCache:
        locking:
          acquireTimeout: "15000"
          concurrencyLevel: "1000"
          striping: "false"
        mode: SYNC
        remoteTimeout: "17500"
        statistics: "true"
parameters:
- name: CLUSTER_NAMESPACE
  description: "The project where the RHDG cluster will be installed."
  required: false
  value: "dg-test-nyc"
- name: CLUSTER_NAME
  description: "The name of the RHDG cluster."
  required: false
  value: "dg-cluster-nyc"