apiVersion: v1
kind: Service
metadata:
  name: my-service-testdg
spec:
  host: mycoolroute.mycluster.mydomain.com
  port:
    targetPort: 2008
  to:
    kind: Service
    name: infinispan-test
    weight: 100
  wildcardPolicy: None