apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rhdg8-cluster
  annotations:
    description: Template to deploy a RHDG cluster on OCP.
    tags: infinispan,datagrid,operator
    iconClass: icon-datagrid
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
objects:
- apiVersion: infinispan.org/v2alpha1
  kind: Batch
  metadata:
    name: "${CLUSTER_NAME}-custom-batch"
  spec:
    cluster: ${CLUSTER_NAME}
    config: |
      put  --cache=operator-cache-03 banana1 world
      put  --cache=operator-cache-03 apple1 world1
      put  --cache=operator-cache-03 apple2 world2
      put  --cache=operator-cache-03 apple3 world3
      put  --cache=operator-cache-03 apple4 world4
      put  --cache=operator-cache-03 apple5 world5
      put  --cache=operator-cache-03 apple6 world6
      put  --cache=operator-cache-03 apple7 world7
      put  --cache=operator-cache-03 apple8 world8
      put  --cache=operator-cache-03 apple9 world9
      put  --cache=operator-cache-03 apple10 world10
parameters:
- name: CLUSTER_NAMESPACE
  description: "The project where the RHDG cluster will be installed."
  required: false
  value: "dg-test-nyc"
- name: CLUSTER_NAME
  description: "The name of the RHDG cluster."
  required: false
  value: "dg-cluster-nyc"