apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rhdg8-cluster
  annotations:
    description: Template to deploy a RHDG cluster on OCP.
    tags: infinispan,datagrid,operator
    iconClass: icon-datagrid
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
objects:
- apiVersion: infinispan.org/v1
  kind: Infinispan
  metadata:
    name: ${CLUSTER_NAME}
    namespace: ${CLUSTER_NAMESPACE}
    annotations:
      infinispan.org/monitoring: 'false'
    labels:
      type: middleware
      prometheus_domain: ${CLUSTER_NAME}
  spec:
    container:
      cpu: '2'
      extraJvmOpts: '-Xlog:gc*=info:file=/tmp/gc.log:time,level,tags,uptimemillis:filecount=10,filesize=1m
              -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/infinispan/server/data -XX:OnError="touch /opt/infinispan/server/data/crash.txt"'
      memory: 0.4Gi
    logging:
      categories: {}
    replicas: 1
    security:
      endpointAuthentication: false
      endpointEncryption:
        type: None
    expose:
      type: LoadBalancer
    image: quay.io/fdemeloj1/dgjcmd:latest
    service:
      type: DataGrid
parameters:
- name: CLUSTER_NAMESPACE
  description: "The project where the RHDG cluster will be installed."
  required: false
  value: "dg-test-lon"
- name: CLUSTER_NAME
  description: "The name of the RHDG cluster."
  required: false
  value: "dg-cluster-on-crash"