apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rhdg8-cluster
  annotations:
    description: Template to deploy a RHDG cluster on OCP.
    tags: infinispan,datagrid,operator
    iconClass: icon-datagrid
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: "${CLUSTER_NAME}-custom-config"
    namespace: ${CLUSTER_NAMESPACE}
  data:
    infinispan-config.xml: >
      <infinispan
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:infinispan:config:13.0 https://infinispan.org/schemas/infinispan-config-13.0.xsd
                                urn:infinispan:server:13.0 https://infinispan.org/schemas/infinispan-server-13.0.xsd"
            xmlns="urn:infinispan:config:13.0"
            xmlns:server="urn:infinispan:server:13.0">  
                  <socket-bindings default-interface="public" port-offset="${infinispan.socket.binding.port-offset:0}">
                   <socket-binding name="memcached" port="11221"/>
                </socket-bindings>    
            <cache-container name="default" statistics="true">
                      <endpoints>
                         <endpoint socket-binding="default" security-realm="default">
                               <memcached-connector socket-binding="memcached"/>
                            </endpoint>
                      </endpoints>
          </infinispan>
parameters:
- name: OPERATOR_NAMESPACE
  description: "The project where the operator will be installed."
  required: false
  value: "dgtest"
- name: CLUSTER_NAMESPACE
  description: "The project where the DG cluster will be installed."
  required: false
  value: "dgtest"
- name: CLUSTER_NAME
  description: "The name of the RHDG cluster."
  required: false
  value: "infinispan-test"