apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rhdg8-cluster
  annotations:
    description: Template to deploy a RHDG cluster on OCP.
    tags: infinispan,datagrid,operator
    iconClass: icon-datagrid
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: "${CLUSTER_NAME}-custom-config"
    namespace: ${CLUSTER_NAMESPACE}
  data:
    infinispan-config.xml: >
      <infinispan
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:infinispan:config:13.0 https://infinispan.org/schemas/infinispan-config-13.0.xsd
                                urn:infinispan:server:13.0 https://infinispan.org/schemas/infinispan-server-13.0.xsd"
            xmlns="urn:infinispan:config:13.0"
            xmlns:server="urn:infinispan:server:13.0">      <cache-container name="default"
                         statistics="true">
          <distributed-cache name="mycacheone"
                             mode="ASYNC"
                             statistics="true">
            <encoding media-type="application/x-protostream"/>
            <expiration lifespan="300000"/>
            <memory max-size="400MB"
                    when-full="REMOVE"/>
          </distributed-cache>
          <distributed-cache name="mycachetwo"
                             mode="SYNC"
                             statistics="true">
            <encoding media-type="application/x-protostream"/>
            <expiration lifespan="300000"/>
            <memory max-size="400MB"
                    when-full="REMOVE"/>
          </distributed-cache>
        </cache-container>
      </infinispan>
parameters:
- name: CLUSTER_NAMESPACE
  description: "The project where the RHDG cluster will be installed."
  required: false
  value: "dg-test-nyc"
- name: CLUSTER_NAME
  description: "The name of the RHDG cluster."
  required: false
  value: "dg-cluster-nyc"