apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rhdg8-caches
  annotations:
    description: Template to configure caches inside a RHDG cluster on OCP.
    tags: infinispan,datagrid,operator
    iconClass: icon-datagrid
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
objects:
- apiVersion: infinispan.org/v2alpha1
  kind: Cache
  metadata:
    name: ${CLUSTER_NAME}-operator-cache-01
    namespace: ${CLUSTER_NAMESPACE}
    labels:
      type: middleware
  spec:
    clusterName: ${CLUSTER_NAME}
    name:  operator-cache-01
    template: >-
      <distributed-cache name="doesnotapply" owners="1" mode="ASYNC" statistics="true">
        <encoding media-type="application/x-protostream"/>
        <state-transfer enabled="false"/>
        <memory>
          <binary eviction="MEMORY" size="400000000"/> <!-- 400 MB -->
        </memory>
        <expiration lifespan="600000"/> <!-- 10 min -->
      </distributed-cache>
- apiVersion: infinispan.org/v2alpha1
  kind: Cache
  metadata:
    name: ${CLUSTER_NAME}-operator-cache-02
    namespace: ${CLUSTER_NAMESPACE}
    labels:
      type: middleware
  spec:
    clusterName: ${CLUSTER_NAME}
    name:  operator-cache-02
    templateName: proto-dist-template
- apiVersion: infinispan.org/v2alpha1
  kind: Cache
  metadata:
    name: ${CLUSTER_NAME}-operator-cache-03
    namespace: ${CLUSTER_NAMESPACE}
    labels:
      type: middleware
  spec:
    clusterName: ${CLUSTER_NAME}
    name:  operator-cache-03
    template: >-
      <distributed-cache name="eu-customers" mode="ASYNC" statistics="true">
        <encoding media-type="application/x-protostream"/>
        <state-transfer enabled="false"/>
        <memory>
          <binary eviction="MEMORY" size="400000000"/> <!-- 400 MB -->
        </memory>
        <expiration lifespan="600000"/> <!-- 10 min -->
          <backups>
          <backup site="SiteB"
                  strategy="ASYNC">
            <state-transfer chunk-size="600"
                            timeout="2400000"
                            max-retries="30"
                            wait-time="2000"
                            mode="AUTO"/>
          </backup>
        </backups>
      </distributed-cache>
parameters:
- name: CLUSTER_NAMESPACE
  description: "The project where the RHDG cluster will be installed."
  required: false
  value: "dg-test-lon"
- name: CLUSTER_NAME
  description: "The name of the RHDG cluster."
  required: false
  value: "dg-cluster-lon"